const bannedWords = [
  // English profanities
  "ass",
  "asshole",
  "bastard",
  "bitch",
  "bollocks",
  "bullshit",
  "crap",
  "cunt",
  "damn",
  "dick",
  "dickhead",
  "fuck",
  "fucker",
  "fucking",
  "hell",
  "motherfucker",
  "nigga",
  "nigger",
  "piss",
  "pussy",
  "shit",
  "shitty",
  "slut",
  "twat",
  "wanker",

  // Sexual or explicit terms
  "blowjob",
  "cock",
  "dildo",
  "dong",
  "faggot",
  "fag",
  "hentai",
  "masturbate",
  "penis",
  "porn",
  "porno",
  "pornography",
  "rape",
  "rapist",
  "scrotum",
  "semen",
  "sex",
  "sperm",
  "testicle",
  "tit",
  "tits",
  "vagina",
  "whore",

  // Hate speech and racial slurs
  "chink",
  "cracker",
  "gook",
  "kike",
  "spic",
  "wetback",

  // Offensive or derogatory phrases
  "fatass",
  "jackass",
  "mother fucker",
  "pussy fucker",
  "son of a bitch",
  "dumbass",

  // Abusive terms
  "idiot",
  "imbecile",
  "moron",
  "retard",
  "stupid",
  "ugly",

  // Religious and cultural offenses
  "jesus christ" /* as an expletive */,
  "goddamn",

  // Bengali profanities (transliterated)
  "bokachoda",
  "chodna",
  "choda",
  "chodni",
  "haraamjada",
  "haraamjadi",
  "khankir chele",
  "khankir pola",
  "khanki",
  "madarchod",
  "petni",
  "shalar chhele",
  "shalar pola",
  "thagachod",
  "haraami",
  "gadha",
  "haramkhor",
  "banchod",
  "boka",

  // Bengali abusive phrases
  "tui ekta boka",
  "tor matha kharap",
  "tor ma ke chudbo",
  "tui boka",
  "shala",
  "shali",
  "poka",

  // Add custom Bengali words in Unicode if needed by chatgpt
  "বোকাচোদা",
  "গুদ",
  "ধোন",
  "চোদ",
  "বাল",
  "ধোনের",
  "গুদের",
  "চোদনা",
  "চোদা",
  "চোদনি",
  "হারামজাদা",
  "হারামজাদি",
  "খানকির ছেলে",
  "খানকির পোলা",
  "খানকি",
  "মাদারচোদ",
  "পেত্নি",
  "শালার ছেলে",
  "ঠগাচোদ",
  "হারামি",
  "গাধা",
  "হারামখোর",
  "বাঞ্চোদ",
  "বোকা",
  "বোকাচোদা",
  "চোদনা",
  "চোদা",
  "চোদনি",
  "হারামজাদা",
  "হারামজাদি",
  "খানকির ছেলে",
  "খানকির পোলা",
  "খানকি",
  "মাদারচোদ",
  "পেত্নি",
  "শালার ছেলে",
  "শালার পোলা",
  "ঠগাচোদ",
  "হারামি",
  "গাধা",
  "হারামখোর",
  "বাঞ্চোদ",
  "বোকা",
  "লুচ্চা",
  "চুলবুলানি",
  "খাইস্টা",
  "পদ্মার চোর",
  "মাগি",
  "ডিম চোর",
  "তোর ভেতর কিছু নাই",
  "চুচি",
  "বাঁশ খাবি",
  "তুই চোদনখোর",
  "তুই খানকি",
  "মাগীর ছেলে",
  "তুই চোষা",
  "চুতমারানি",
  "চুতিয়া",
  "চুদে ফেলা",
  "গুদ চাটা",
  "মাদারচোদ",
  "তোর গুদ মারবো",
  "তুই গুদমারানী",
  "বাপচোদ",
  "গাভীচোদ",
  "গু খাবি",
  "গু খা",
  "গু চাটা",
  "চুচি চাটা",
  "মাই চাটা",
  "পাছা চাটা",
  "খানকির বাচ্চা",
  "তোর মাকে চুদবো",
  "তোর বোনকে চুদবো",
  "গুদ চিরবো",
  "গুদ ফাটাবো",
  "গু মারবো",
  "চোদ খা",
  "চুত মাইরা দিবো",
  "মাগীর পোলা",
  "খানকির গুদ",
  "খানকির মাই",
  "খানকির পাছা",
  "মদ খাইবি",
  "চুদা",
  "চুদতে আস",
  "খানকি মাগি",
  "তোর গুদ ফাটাবো",

  // Catch-all for anything else specific to your audience
  "examplebadword1",
  "examplebadword2",
];
export default bannedWords;
